version: '3'
services:
  proxy: #reverse proxy와 로드밸런싱을 위한 nginx
    image: nginx:latest
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
  express_1:
    build:
      context: .
    container_name: express1
    expose:
      - "3000" #첫번쨰 노드 서버는 3000번
    restart: "unless-stopped"
  express_2:
    build:
      context: .
    container_name: express2
    expose:
      - "3000"
    restart: "unless-stopped"
  express_3:
    build:
      context: .
    container_name: express3
    expose:
      - "3000"
    restart: "unless-stopped"
  express_4:
    build:
      context: .
    container_name: express4
    expose:
      - "3000"
    restart: "unless-stopped"